object Modules {
    const val app = ":app"
    const val core = ":core"
    const val core_ui = ":core-ui"
    const val navigation = ":navigation"
    const val splash = ":feature-splash-screen"
    const val auth_api = ":feature-auth:api"
    const val auth_impl = ":feature-auth:impl"
    const val address_api = ":feature-address:api"
    const val address_impl = ":feature-address:impl"
    const val registration_api = ":feature-registration:api"
    const val registration_impl = ":feature-registration:impl"
    const val profile_api = ":feature-profile:api"
    const val profile_impl = ":feature-profile:impl"
    const val order_api = ":feature-order:api"
    const val order_impl = ":feature-order:impl"
}