object Versions {
    const val retrofit = "2.9.0"
    const val koin = "3.2.2"
    const val coil = "2.2.2"
    const val androidxFragments = "1.5.4"
    const val androidxBrowser = "1.4.0"
    const val androidxCore = "1.9.0"
    const val androidxAppCompat = "1.5.1"
    const val androidxRecycler = "1.2.1"
    const val material = "1.7.0"
    const val androidxCardview = "1.0.0"
    const val constraintLayout = "2.1.4"
    const val cicerone = "7.1"
    const val viewmodel = "2.5.1"
    const val lifecycleExt = "2.5.1"
    const val room = "2.4.3"
    const val gson = "2.10"
    const val adapterDelegates = "4.3.2"
    const val splashScreen = "1.0.0"
}