object Versions {
    const val retrofit = "2.9.0"
    const val koin = "3.2.2"
    const val coil = "2.2.2"
    const val androidxCore = "1.9.0"
    const val room = "2.4.3"
    const val material = "1.7.0"
    const val gson = "2.10"
    const val splashScreen = "1.0.0"
    const val detekt = "1.22.0"
    const val compose = "1.3.1"
    const val activityCompose = "1.6.1"
    const val lifecycle = "2.5.1"
    const val kViewModel = "0.11"
    const val odyssey = "1.0.1"
}