object Versions {
    const val retrofit = "2.9.0"
    const val koin = "3.2.2"
    const val coil = "2.2.2"
    const val androidxCore = "1.9.0"
    const val room = "2.4.3"
    const val material = "1.7.0"
    const val gson = "2.10"
    const val splashScreen = "1.0.0"
    const val detekt = "1.22.0"
    const val compose = "1.3.1"
    const val activityCompose = "1.6.1"
    const val lifecycle = "2.5.1"
    const val kViewModel = "0.11"
    const val odyssey = "1.3.0"
    const val serialization = "1.3.3"
    const val okhttp = "4.10.0"
    const val kotlin = "1.7.10"
    const val kotlinCoroutines = "1.5.2"
    const val crypto = "1.1.0-alpha04"
    const val firebaseMessaging = "23.1.1"
    const val firebaseCrashlytics = "18.3.3"
}